### ISSUE TITLE
code validation in widgets

### ISSUE THREAD

**Issue by lisaannerager** [tarakc02/discoveryengine#64]
Hi Tarak-

I was trying to build a query to pull all families in the bay area with rated or implied capacity that HAVE NOT been met by a fundraiser and weren't DQed per a contact report.  When I spot-checked my results, there were def some families that HAD visits recorded in contact reports, so, wondering what I screwed up? Code below. 

I used the following predicates:
current_student = has_reunion_year(2021,2020,219,2018)

current_parent = parent_of(current_student)

current_bay_family = current_parent %and% lives_in_msa(41860, 41940, 42220, 40900)

capacity = has_capacity(1,2,3,7,5,6,7,8,9) %or% has_implied_capacity(MORE, MOST)

bay_family_with_capacity = current_bay_family %and% capacity

dq_outcomes = contact_outcome(DISQU)
dqed_prospects = contacted_entity_of(dq_outcomes)

visit = contact_purpose(VISIT)
visits = contacted_entity_of(visit)

unvisited_bay_families_of_interest = (bay_family_with_capacity %but_not% dqed_prospects) %but_not% visits

**Comment by tarakc02** [comment]
Hi @lisaannerager,

The definition of `visit` near the end of your code should be:

```
visit = contact_type(V)
```

Because visit is coded as the "type" of the contact and not the "purpose," and the code is `V`, not `VISIT`. That should solve the specific problem you're having right now, but I'm leaving this issue open so that we can consider options for warnings/error messages if a non-existent code is supplied (there is no contact purpose code "VISIT" so it would help to give some feedback to that effect when you run `contact_purpose(VISIT)`). 

Sidenote: This wasn't what you asked about, but I noticed a couple of typos in the definition of `capacity` and `current_student`. When specifying a sequence of numbers all in a row like that, you can cut down on possible typos by using the colon `:` to denote a range:

```
current_student = has_reunion_year(2018:2021)
capacity = has_capacity(1:9) %or% has_implied_capacity(MORE, MOST)
```

**Comment by lisaannerager** [comment]
Thank you!


Lisa Rager

Senior Prospect Analyst

University Development and Alumni Relations

510-642-2581

lrager@berkeley.edu
